### ISSUE TITLE
installation failure

### ISSUE THREAD

**Issue by Daisy-GENG** [borchero/pycave#17]
Hi,

I am trying to install pycave using `pip3 install pycave` , but I get the following error:

`ERROR: Could not find a version that satisfies the requirement pycave (from versions: none)
ERROR: No matching distribution found for pycave`

I've already updated my pip version to the latest version, and I can successfully install other available packages using `pip3 install`. Is there something wrong with my python environment? 

Thanks.
Daisy

**Comment by borchero** [comment]
Hey Daisy,
which version of Python are you using? PyCave requires Python version `3.8` or `3.9`.

**Comment by Daisy-GENG** [comment]
Hi,

Sorry, I am currently using python 3.6. After upgrading my python version to 3.8, everything works well.

Thank you so much!
Daisy
