### ISSUE TITLE
side by side between pycave and sklearn

### ISSUE THREAD

**Issue by groadabike** [borchero/pycave#2]
Hi @borchero,
I want to confirm if I understood correctly the output of the GMM methods. If I compare with sklearn, is this table correct?

 | sklearn method | pycave equivalent (pc_gmm) |
 |---|---|
 | predict | argmax(pc_gmm.predict(data)) |
 | predict_proba |  pc_gmm.predict(data) |
 | score |  pc_gmm.evaluate(data, reduction='mean') |
 | score_samples | pc_gmm.evaluate(data, reduction=None) |
 | sample | pc_gmm.sample(n=##) |

Thank you so much

**Comment by borchero** [comment]
Yes, that sounds about right!

One thing to take care: during training, sklearn outputs the total NLL as loss instead of the per-datapoint NLL (so you might observe largely differing loss values when comparing the two frameworks).
