### ISSUE TITLE
New feature: recover weights, means and covariance.

### ISSUE THREAD

**Issue by groadabike** [borchero/pycave#4]
Hi @borchero,
Is it possible to add three methods or attributes to return the weights, means and covariances?
The covariances would be especially useful to analyse the model when we have "singleton datapoint".

Thank you

**Comment by borchero** [comment]
You should just be able to access the models parameters. Run `list(gmm.named_parameters())` to get an overview of the names (I guess it's `component_weights`, `gaussian.means` and `gaussian.covars`). Does that help you?

**Comment by groadabike** [comment]
Yes, that makes sense. 
Thank you
