### ISSUE TITLE
mini-batch training GMM sample

### ISSUE THREAD

**Issue by Learningm** [borchero/pycave#7]
Could you please provide a mini-batch training GMM sample using cpu/gpu? I am interested in your work, and want to train a GMM model on a large data, about 100G. Consider we have a (10m, 128) feature vector now. Thanks !

**Comment by borchero** [comment]
You can just use PyTorch concept of datasets and data loaders. For now, let's assume that you have a single data matrix `X` of shape `[10m, 128]` (for 100GB you might want to look for alternatives though).

You can then initialize a dataset and pass a data loader to the `fit` method:

```python
from torch.utils.data import TensorDataset, DataLoader

data = TensorDataset(X)
loader = DataLoader(data, num_workers=0)
gmm.fit(loader)
```

**Comment by Learningm** [comment]
> You can just use PyTorch's concept of datasets and data loaders. For now, let's assume that you have a single data matrix `X` of shape `[10m, 128]` (for 100GB you might want to look for alternatives though).
> 
> You can then initialize a dataset and pass a data loader to the `fit` method:
> 
> ```python
> from torch.utils.data import TensorDataset, DataLoader
> 
> data = TensorDataset(X)
> loader = DataLoader(data, num_workers=0, batch_size=8192)
> gmm.fit(loader)
> ```

it seems not working. data is a parameter with (3m, 80) size.
Here's my test code:

`def batch_learning_gmm(data):
    data = torch.Tensor(data)
    tensor_data = TensorDataset(data)
    loader = DataLoader(tensor_data, num_workers=4, batch_size = 1024)
    gmm = GMM(num_components=256, num_features=80)
    # gmm.reset_parameters(loader)
    history = gmm.fit(loader, gpu=False)`

If I uncomment the reset_parameter function, I get an error below:
Traceback (most recent call last):
  File "test.py", line 188, in <module>
    batch_learning_gmm(folder_feature)
  File "test.py", line 173, in batch_learning_gmm
    gmm.reset_parameters(loader)
  File "~/anaconda3/envs/svm_test/lib/python3.8/site-packages/pycave/bayes/gmm/model.py", line 113, in reset_parameters
    labels = self.gaussian.reset_parameters(data, max_iter, reg=reg)
  File "~/anaconda3/envs/svm_test/lib/python3.8/site-packages/pycave/bayes/_internal/output.py", line 211, in reset_parameters
    model.fit(data.cpu().numpy())
AttributeError: 'DataLoader' object has no attribute 'cpu'

If I comment the function, I got another error below:
Traceback (most recent call last):
  File "test.py", line 188, in <module>
    batch_learning_gmm(folder_feature)
  File "test.py", line 174, in batch_learning_gmm
    history = gmm.fit(loader, gpu=False)
  File "~/anaconda3/envs/svm_test/lib/python3.8/site-packages/pyblaze/nn/utils/estimator.py", line 51, in fit
    return self.engine.train(data, *args, **kwargs)
  File "~/anaconda3/envs/svm_test/lib/python3.8/site-packages/pyblaze/nn/engine/base.py", line 195, in train
    loss = self.train_batch(item, **train_kwargs)
  File "~/anaconda3/envs/svm_test/lib/python3.8/site-packages/pycave/bayes/gmm/engine.py", line 66, in train_batch
    responsibilities, nll = self.model(data)
  File "~/anaconda3/envs/svm_test/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "~/anaconda3/envs/svm_test/lib/python3.8/site-packages/pycave/bayes/gmm/model.py", line 141, in forward
    probs = self.gaussian.evaluate(data, log=True)
  File "~/anaconda3/envs/svm_test/lib/python3.8/site-packages/pycave/bayes/_internal/output.py", line 234, in evaluate
    shape = data.size()
AttributeError: 'list' object has no attribute 'size'

Thanks!

**Comment by groadabike** [comment]
Hi,
1. You can always create your own Dataset

```Python
from torch.utils.data import Dataset
import torch
import numpy as np

class MyDataset(Dataset):
    def __init__(self, data):
        self.data = data
        self.len = len(self.data)

    def __getitem__(self, index):
        x = torch.from_numpy(self.data[index].astype(np.float32))
        return x

    def __len__(self):
        return self.len
```
Then, use as:

```Python
from torch.utils.data import DataLoader

fvector = np.random.rand(1000,50)
dataset = MyDataset(fvector)
loader = DataLoader(test_dataset,
                                 batch_size=50000,
                                 shuffle=True,
                                 num_workers=0)

gmm = GMM(num_components=256, num_features=80)
# Reset expects a tensor
gmm.reset_parameters(torch.Tensor(fvectors[:500].astype(np.float32)))
history = gmm.fit(loader, gpu=False)
```

As you can see in reset_parameters, it expects a tensor, not a dataloader.
https://github.com/borchero/pycave/blob/691179be4340ec3f9757faf3c73dfbab6200490e/pycave/bayes/gmm/model.py#L90

Hope this help
Cheers

**Comment by Learningm** [comment]
> Hi,
> 
> 1. You can always create your own Dataset
> 
> ```python
> from torch.utils.data import Dataset
> import torch
> import numpy as np
> 
> class MyDataset(Dataset):
>     def __init__(self, data):
>         self.data = data
>         self.len = len(self.data)
> 
>     def __getitem__(self, index):
>         x = torch.from_numpy(self.data[index].astype(np.float32))
>         return x
> 
>     def __len__(self):
>         return self.len
> ```
> 
> Then, use as:
> 
> ```python
> from torch.utils.data import DataLoader
> 
> fvector = np.random.rand(1000, 80)
> dataset = MyDataset(fvector)
> loader = DataLoader(test_dataset,
>                                  batch_size=50,
>                                  shuffle=True,
>                                  num_workers=0)
> 
> gmm = GMM(num_components=256, num_features=80)
> # Reset expects a tensor
> gmm.reset_parameters(torch.Tensor(fvectors[:500].astype(np.float32)))
> history = gmm.fit(loader, gpu=False)
> ```
> 
> As you can see in reset_parameters, it expects a tensor, not a dataloader.
> https://github.com/borchero/pycave/blob/691179be4340ec3f9757faf3c73dfbab6200490e/pycave/bayes/gmm/model.py#L90
> 
> Hope this help
> Cheers

Cool, I got it, thanks!
